#!/bin/sh

juju-log "Installing OpenJDK"
apt-get install -y openjdk-6-jre charm-helper-sh

juju-log "Add Minecraft init script"
cp opt/minecraft /etc/init/minecraft.conf

juju-log "Downloading Minecraft"
mkdir -p /opt/minecraft/
wget "https://s3.amazonaws.com/MinecraftDownload/launcher/minecraft_server.jar" -O /opt/minecraft/minecraft_server.jar
